name: Test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  FORCE_COLOR: 3

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: ["14.17", "lts/*", "latest"]

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: yarn install --frozen-lockfile

    - run: yarn test
    
  release:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - uses: actions/checkout@v3

      - name: Setup semantic-release
        run: npm install -g semantic-release @semantic-release/git @semantic-release/github @semantic-release/npm @semantic-release/changelog -D

      - name: Release
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

    